backend:
  name: github
  repo: mkrochlice/mkrochlice.github.io
  branch: main
  base_url: https://mkrochliceoauth.mmq.cz
media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"
collections:
  - name: "aktuality"
    label: "Aktuality"
    folder: "aktuality/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Titulek", name: "title", widget: "string" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Obsah", name: "body", widget: "markdown" }
  - name: "zapisy"
    label: "Zápisy ze schůzí"
    folder: "zapisy/_posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "zapis" }
      - { label: "Číslo jednání", name: "title", widget: "string" }
      - { label: "Datum jednání", name: "date", widget: "datetime" }
      - { label: "Přítomni", name: "present", widget: "string" }
      - { label: "Omluveni", name: "excused", widget: "string" }
      - { label: "Neomluveni", name: "unexcused", widget: "string" }
      - { label: "Hosté", name: "guests", widget: "string" }
      - { label: "Obsah", name: "body", widget: "markdown" }
  - name: "static"
    label: "Statický obsah"
    folder: "/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Titulek", name: "title", widget: "string" }
      - { label: "Obsah", name: "body", widget: "markdown" }
  - label: "Konfigurace"
    name: "data"
    files:
      - label: "Navigace"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Stránky"
            name: "sites"
            widget: "list"
            fields:
            - { label: "Jméno", name: "name", widget: "string" }
            - { label: "Adresa", name: "link", widget: "string" }
