backend:
  name: github
  repo: mkrochlice/mkrochlice.github.io
  branch: main
media_folder: "uploads"
public_folder: "/"
collections:
  - name: "aktuality"
    label: "Aktuality"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Titulek", name: "title", widget: "string" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Obsah", name: "body", widget: "markdown" }
  - name: "static"
    label: "Statický obsah"
    folder: "/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Titulek", name: "title", widget: "string" }
      - { label: "Obsah", name: "body", widget: "markdown" }

